### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by binoculars** [quipt/monorepo#1188]
Hi @jbesw 👋 I thought I might share my app with you. It's a working example of Angular, Auth0, and a bunch of AWS serverless technologies mixed in. The UI is pretty basic but it has the functionality to do your normal CRUD operations. It should be intuitive enough to figure out, I hope. If you have some time, please check it out. I will certainly take any feedback you might have. Thanks!

**Comment by jbesw** [comment]
This is very interesting! We have some reference examples we give to developers, so I'll add this to the Angular collection. Thanks for sharing!
